name: dart_appwrite
version: 4.0.2
description: Appwrite is an open-source self-hosted backend server that abstract and simplify complex and repetitive development tasks behind a very simple REST API
homepage: https://appwrite.io
repository: https://github.com/appwrite/sdk-for-dart
issue_tracker: https://github.com/appwrite/sdk-generator/issues
documentation: https://appwrite.io/support
environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  http: ^0.13.4

dev_dependencies:
  test: ^1.16.8
  lints: ^1.0.1