name: dart_appwrite
version: 9.0.2
description: Appwrite is an open-source self-hosted backend server that abstract and simplify complex and repetitive development tasks behind a very simple REST API
homepage: https://appwrite.io
repository: https://github.com/appwrite/sdk-for-dart
issue_tracker: https://github.com/appwrite/sdk-generator/issues
documentation: https://appwrite.io/support
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  http: '>=0.13.6 <1.0.1'

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
  mockito: ^5.4.0
