name: dart_appwrite
version: 12.2.0
description: Appwrite is an open-source self-hosted backend server that abstract and simplify complex and repetitive development tasks behind a very simple REST API
homepage: https://appwrite.io
repository: https://github.com/appwrite/sdk-for-dart
issue_tracker: https://github.com/appwrite/sdk-generator/issues
documentation: https://appwrite.io/support
environment:
  sdk: '>=2.17.0 <4.0.0'
dependencies:
  http: '>=0.13.6 <2.0.0'

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
  mockito: ^5.4.4
