name: dart_appwrite
version: 0.6.1
description: Appwrite is an open-source self-hosted backend server that abstract and simplify complex and repetitive development tasks behind a very simple REST API
homepage: https://appwrite.io
repository: https://github.com/appwrite/sdk-for-dart
issue_tracker: https://github.com/appwrite/sdk-generator/issues
documentation: https://appwrite.io/support
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  dio: ^4.0.0

dev_dependencies:
  test: ^1.16.8